// ============================================================
// Mock Data — Sivili Furniture Store
// No database needed for MVP; data lives here in memory.
// ============================================================

export type Category = {
  id: string;
  nameKey: string;
  icon: string;
  slug: string;
};

export type Product = {
  id: string;
  name: string;
  nameEn: string;
  nameTh: string;
  nameZh: string;
  nameJa: string;
  nameLa: string;
  category: string;
  price: number;
  originalPrice?: number;
  material: string;
  dimensions: string;
  brand: string;
  colors: string[];
  images: string[];
  description: string;
  descriptionTh: string;
  stock: number;
  rating: number;
  reviewCount: number;
  isFeatured: boolean;
  isNew: boolean;
};

export type User = {
  id: string;
  name: string;
  email: string;
  password: string;
  role: 'admin' | 'customer';
  createdAt: string;
};

export type Order = {
  id: string;
  userId: string;
  items: { productId: string; quantity: number; price: number }[];
  total: number;
  status: 'pending' | 'confirmed' | 'shipping' | 'delivered' | 'cancelled';
  paymentMethod: 'credit_card' | 'qr_code' | 'mobile_banking';
  createdAt: string;
};

export const CATEGORIES: Category[] = [
  { id: 'living', nameKey: 'cat_living', icon: '🛋️', slug: 'living-room' },
  { id: 'bedroom', nameKey: 'cat_bedroom', icon: '🛏️', slug: 'bedroom' },
  { id: 'dining', nameKey: 'cat_dining', icon: '🍽️', slug: 'dining-room' },
  { id: 'office', nameKey: 'cat_office', icon: '💼', slug: 'office' },
  { id: 'outdoor', nameKey: 'cat_outdoor', icon: '🌿', slug: 'outdoor' },
];

// Product image placeholders from Unsplash (furniture images)
const FURNITURE_IMAGES = {
  sofa: [
    'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80',
    'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=800&q=80',
    'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=800&q=80',
  ],
  bed: [
    'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800&q=80',
    'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80',
    'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=800&q=80',
  ],
  dining: [
    'https://images.unsplash.com/photo-1577140917170-285929fb55b7?w=800&q=80',
    'https://images.unsplash.com/photo-1615529162924-f8605388461d?w=800&q=80',
    'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80',
  ],
  office: [
    'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800&q=80',
    'https://images.unsplash.com/photo-1547474874-60e0b05d98e2?w=800&q=80',
    'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800&q=80',
  ],
  outdoor: [
    'https://images.unsplash.com/photo-1600210492493-0946911123ea?w=800&q=80',
    'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    'https://images.unsplash.com/photo-1555554282-d3e18c5e00cd?w=800&q=80',
  ],
  wardrobe: [
    'https://images.unsplash.com/photo-1558997519-83ea9252edf8?w=800&q=80',
    'https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=800&q=80',
    'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80',
  ],
  chair: [
    'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=800&q=80',
    'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80',
    'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=800&q=80',
  ],
  table: [
    'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80',
    'https://images.unsplash.com/photo-1530018352490-a5c3069c3b3e?w=800&q=80',
    'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80',
  ],
};

export const PRODUCTS: Product[] = [
  {
    id: 'p001',
    name: 'Nordic Comfort Sofa',
    nameEn: 'Nordic Comfort Sofa',
    nameTh: 'โซฟานอร์ดิก คอมฟอร์ต',
    nameZh: '北欧舒适沙发',
    nameJa: 'ノルディックコンフォートソファ',
    nameLa: 'ໂຊຟານໍດິກ ຄອມຟອດ',
    category: 'living',
    price: 32900,
    originalPrice: 38000,
    material: 'ผ้าลินิน / Linen Fabric',
    dimensions: '220 × 95 × 85 cm',
    brand: 'Sivili Home',
    colors: ['#F5F0E8', '#5B6B7A', '#8B7355'],
    images: FURNITURE_IMAGES.sofa,
    description: 'Elegant 3-seater sofa crafted with premium linen fabric. Perfect for modern living spaces.',
    descriptionTh: 'โซฟา 3 ที่นั่ง ผ้าลินินพรีเมียม ดีไซน์สไตล์นอร์ดิก เหมาะกับห้องนั่งเล่นทันสมัย',
    stock: 12,
    rating: 4.8,
    reviewCount: 124,
    isFeatured: true,
    isNew: false,
  },
  {
    id: 'p002',
    name: 'Serenity King Bed Frame',
    nameEn: 'Serenity King Bed Frame',
    nameTh: 'เตียงคิงไซซ์ เซเรนิตี้',
    nameZh: '宁静系列大床架',
    nameJa: 'セレニティキングベッドフレーム',
    nameLa: 'ກອບຕຽງ ເຊລີນິຕີ ຂະໜາດ King',
    category: 'bedroom',
    price: 45000,
    originalPrice: 52000,
    material: 'ไม้สักแท้ / Solid Teak Wood',
    dimensions: '200 × 200 × 120 cm',
    brand: 'Sivili Home',
    colors: ['#8B6914', '#5C4A37', '#2C1810'],
    images: FURNITURE_IMAGES.bed,
    description: 'Luxurious king-size bed frame in solid teak wood with a timeless design.',
    descriptionTh: 'กรอบเตียงคิงไซซ์ ไม้สักแท้ ดีไซน์คลาสสิก ทนทาน อบอุ่น',
    stock: 8,
    rating: 4.9,
    reviewCount: 87,
    isFeatured: true,
    isNew: false,
  },
  {
    id: 'p003',
    name: 'Harvest Dining Set 6',
    nameEn: 'Harvest Dining Set 6',
    nameTh: 'ชุดโต๊ะทานข้าว ฮาร์เวสต์ 6 ที่นั่ง',
    nameZh: '丰收六人餐桌套装',
    nameJa: 'ハーベスト6人用ダイニングセット',
    nameLa: 'ຊຸດໂຕະກິນເຂົ້າ ຮາດເວສ 6 ທີ່ນັ່ງ',
    category: 'dining',
    price: 28500,
    material: 'ไม้ยางพารา / Rubber Wood',
    dimensions: 'โต๊ะ: 160 × 80 × 75 cm',
    brand: 'Sivili Home',
    colors: ['#D4A96A', '#8B6914'],
    images: FURNITURE_IMAGES.dining,
    description: 'Complete 6-seater dining set with rubber wood table and matching chairs.',
    descriptionTh: 'ชุดโต๊ะทานข้าว 6 ที่นั่ง ไม้ยางพาราคุณภาพสูง พร้อมเก้าอี้ครบชุด',
    stock: 5,
    rating: 4.6,
    reviewCount: 56,
    isFeatured: true,
    isNew: true,
  },
  {
    id: 'p004',
    name: 'Executive Ergonomic Chair',
    nameEn: 'Executive Ergonomic Chair',
    nameTh: 'เก้าอี้ผู้บริหาร เออร์กอนอมิก',
    nameZh: '行政人体工程学椅',
    nameJa: 'エグゼクティブエルゴノミクスチェア',
    nameLa: 'ເກົ້າອີ້ຜູ້ບໍລິຫານ ເອີກໂກໂນມິກ',
    category: 'office',
    price: 18900,
    originalPrice: 22000,
    material: 'ตาข่ายหายใจ / Breathable Mesh',
    dimensions: '65 × 65 × 110-125 cm',
    brand: 'ErgoSivili',
    colors: ['#1E3A5F', '#2C2C2C', '#FFFFFF'],
    images: FURNITURE_IMAGES.office,
    description: 'Premium ergonomic office chair with lumbar support and adjustable armrests.',
    descriptionTh: 'เก้าอี้ทำงานเออร์กอนอมิก รองรับหลังส่วนล่าง ปรับได้หลายระดับ',
    stock: 20,
    rating: 4.7,
    reviewCount: 203,
    isFeatured: false,
    isNew: false,
  },
  {
    id: 'p005',
    name: 'Garden Rattan Lounge Set',
    nameEn: 'Garden Rattan Lounge Set',
    nameTh: 'ชุดเก้าอี้สนามหวาย การ์เดน',
    nameZh: '花园藤编休闲套装',
    nameJa: 'ガーデンラタンラウンジセット',
    nameLa: 'ຊຸດເກົ້າອີ້ສະຫວ່ງ ຫວາຍ ການ໌ດ໌',
    category: 'outdoor',
    price: 16500,
    material: 'หวายสังเคราะห์ / Synthetic Rattan',
    dimensions: 'โต๊ะ: 100 × 60 × 45 cm',
    brand: 'Sivili Outdoor',
    colors: ['#8B6914', '#5C4A37'],
    images: FURNITURE_IMAGES.outdoor,
    description: 'Weather-resistant synthetic rattan lounge set for gardens and balconies.',
    descriptionTh: 'ชุดเก้าอี้สนามหวายสังเคราะห์ กันน้ำ กันแดด เหมาะกับระเบียงและสวน',
    stock: 15,
    rating: 4.5,
    reviewCount: 42,
    isFeatured: false,
    isNew: true,
  },
  {
    id: 'p006',
    name: 'Minimal Wardrobe 4-Door',
    nameEn: 'Minimal Wardrobe 4-Door',
    nameTh: 'ตู้เสื้อผ้า 4 บาน มินิมอล',
    nameZh: '简约四门衣柜',
    nameJa: 'ミニマル4ドアワードローブ',
    nameLa: 'ຕູ້ເສື້ອຜ້າ 4 ບານ ມິນິມານ',
    category: 'bedroom',
    price: 21500,
    material: 'ไม้ MDF + ผิว PVC / MDF + PVC',
    dimensions: '200 × 60 × 220 cm',
    brand: 'Sivili Home',
    colors: ['#FFFFFF', '#F5F0E8', '#2C2C2C'],
    images: FURNITURE_IMAGES.wardrobe,
    description: 'Modern 4-door wardrobe with smart interior organization and soft-close hinges.',
    descriptionTh: 'ตู้เสื้อผ้า 4 บาน ดีไซน์มินิมอล บานพับนุ่มนวล จัดระเบียบภายในได้ดี',
    stock: 7,
    rating: 4.4,
    reviewCount: 68,
    isFeatured: false,
    isNew: false,
  },
  {
    id: 'p007',
    name: 'Zen Accent Armchair',
    nameEn: 'Zen Accent Armchair',
    nameTh: 'เก้าอี้แอคเซนต์ เซน',
    nameZh: '禅意单人椅',
    nameJa: 'ゼンアクセントアームチェア',
    nameLa: 'ເກົ້າອີ້ ເຊນ ແອກເຊນ',
    category: 'living',
    price: 9900,
    originalPrice: 12000,
    material: 'ผ้าเวลเวต / Velvet Fabric',
    dimensions: '75 × 80 × 90 cm',
    brand: 'Sivili Home',
    colors: ['#1E3A5F', '#8B7355', '#4A7C59'],
    images: FURNITURE_IMAGES.chair,
    description: 'Cozy velvet accent chair perfect as a reading nook companion.',
    descriptionTh: 'เก้าอี้เวลเวตสบาย เหมาะเป็นมุมอ่านหนังสือในห้องนั่งเล่น',
    stock: 18,
    rating: 4.6,
    reviewCount: 91,
    isFeatured: true,
    isNew: false,
  },
  {
    id: 'p008',
    name: 'Oslo Coffee Table',
    nameEn: 'Oslo Coffee Table',
    nameTh: 'โต๊ะกาแฟ ออสโล',
    nameZh: '奥斯陆茶几',
    nameJa: 'オスロコーヒーテーブル',
    nameLa: 'ໂຕະກາເຟ ອ໋ອສໂລ',
    category: 'living',
    price: 7500,
    material: 'ไม้สัก + กระจกนิรภัย / Teak + Tempered Glass',
    dimensions: '120 × 60 × 45 cm',
    brand: 'Sivili Home',
    colors: ['#8B6914', '#2C2C2C'],
    images: FURNITURE_IMAGES.table,
    description: 'Sleek Scandinavian coffee table combining solid teak and tempered glass.',
    descriptionTh: 'โต๊ะกลางห้องนั่งเล่นสไตล์สแกนดิเนเวีย ไม้สักผสมกระจกนิรภัย',
    stock: 25,
    rating: 4.7,
    reviewCount: 115,
    isFeatured: false,
    isNew: false,
  },
  {
    id: 'p009',
    name: 'Classic Study Desk',
    nameEn: 'Classic Study Desk',
    nameTh: 'โต๊ะทำงานคลาสสิก',
    nameZh: '经典书桌',
    nameJa: 'クラシックスタディデスク',
    nameLa: 'ໂຕະເຮັດວຽກ ຄລາດສິກ',
    category: 'office',
    price: 12500,
    material: 'ไม้ยางพารา / Rubber Wood',
    dimensions: '140 × 70 × 76 cm',
    brand: 'ErgoSivili',
    colors: ['#8B6914', '#5C4A37', '#FFFFFF'],
    images: FURNITURE_IMAGES.office,
    description: 'Timeless solid wood study desk with cable management and storage drawer.',
    descriptionTh: 'โต๊ะทำงานไม้ยางพาราคลาสสิก มีลิ้นชักเก็บของ จัดสายได้เรียบร้อย',
    stock: 10,
    rating: 4.5,
    reviewCount: 77,
    isFeatured: false,
    isNew: false,
  },
  {
    id: 'p010',
    name: 'Cloud Queen Mattress',
    nameEn: 'Cloud Queen Mattress',
    nameTh: 'ที่นอนควีนไซซ์ คลาวด์',
    nameZh: '云朵皇后床垫',
    nameJa: 'クラウドクイーンマットレス',
    nameLa: 'ທີ່ນອນ Queen ຄລາວດ໌',
    category: 'bedroom',
    price: 15900,
    originalPrice: 19000,
    material: 'เมมโมรี่โฟม / Memory Foam',
    dimensions: '160 × 200 × 25 cm',
    brand: 'SleepSivili',
    colors: ['#FFFFFF', '#F5F0E8'],
    images: FURNITURE_IMAGES.bed,
    description: 'Premium memory foam queen mattress with cooling gel layer for all-night comfort.',
    descriptionTh: 'ที่นอนเมมโมรี่โฟมควีนไซซ์ ชั้น Cooling Gel นอนหลับสบายตลอดคืน',
    stock: 30,
    rating: 4.9,
    reviewCount: 256,
    isFeatured: true,
    isNew: false,
  },
  {
    id: 'p011',
    name: 'Balcony Bistro Chair Pair',
    nameEn: 'Balcony Bistro Chair Pair',
    nameTh: 'คู่เก้าอี้ระเบียง บิสโทร',
    nameZh: '阳台小酒馆椅子一对',
    nameJa: 'バルコニービストロチェアペア',
    nameLa: 'ຄູ່ເກົ້າອີ້ລະບຽງ ບິດສໂຕ',
    category: 'outdoor',
    price: 5800,
    material: 'เหล็กกล้าไร้สนิม / Stainless Steel',
    dimensions: '45 × 52 × 82 cm (each)',
    brand: 'Sivili Outdoor',
    colors: ['#FFFFFF', '#1E3A5F', '#2C2C2C'],
    images: FURNITURE_IMAGES.outdoor,
    description: 'Powder-coated bistro chairs, rust-proof and UV-resistant for outdoor use.',
    descriptionTh: 'เก้าอี้บิสโทรเหล็กกล้า เคลือบผง กันสนิม กันรังสี UV เหมาะกับระเบียงบ้าน',
    stock: 40,
    rating: 4.3,
    reviewCount: 33,
    isFeatured: false,
    isNew: true,
  },
  {
    id: 'p012',
    name: 'Luxe Velvet Dining Chair',
    nameEn: 'Luxe Velvet Dining Chair',
    nameTh: 'เก้าอี้ทานข้าวเวลเวตหรูหรา',
    nameZh: '豪华丝绒餐椅',
    nameJa: 'ラグジュアリーベルベットダイニングチェア',
    nameLa: 'ເກົ້າອີ້ກິນເຂົ້າ ຜ້າ Velvet ຫຼູຫຼາ',
    category: 'dining',
    price: 4200,
    material: 'ผ้าเวลเวต + โครงเหล็ก / Velvet + Steel',
    dimensions: '50 × 55 × 90 cm',
    brand: 'Sivili Home',
    colors: ['#1E3A5F', '#8B7355', '#2C2C2C', '#FFFFFF'],
    images: FURNITURE_IMAGES.chair,
    description: 'Elegant velvet dining chair with gold-tone steel legs, sold individually.',
    descriptionTh: 'เก้าอี้ทานข้าวผ้าเวลเวตหรูหรา ขาเหล็กชุบทอง ราคาต่อตัว',
    stock: 48,
    rating: 4.5,
    reviewCount: 62,
    isFeatured: false,
    isNew: false,
  },
  {
    id: 'p013',
    name: 'Compact TV Console 150cm',
    nameEn: 'Compact TV Console 150cm',
    nameTh: 'ตู้วางทีวี คอมแพค 150 ซม.',
    nameZh: '紧凑型电视柜150cm',
    nameJa: 'コンパクトテレビコンソール150cm',
    nameLa: 'ຕູ້ວາງທີວີ 150 ຊມ',
    category: 'living',
    price: 8900,
    material: 'MDF เคลือบผิวไม้ / Wood-veneer MDF',
    dimensions: '150 × 40 × 50 cm',
    brand: 'Sivili Home',
    colors: ['#F5F0E8', '#2C2C2C', '#8B6914'],
    images: FURNITURE_IMAGES.table,
    description: 'Modern TV console with open shelving and concealed cable management.',
    descriptionTh: 'ตู้วางทีวีทันสมัย ชั้นวางเปิด จัดสายไฟในตัว เหมาะห้องนั่งเล่น',
    stock: 14,
    rating: 4.4,
    reviewCount: 48,
    isFeatured: false,
    isNew: false,
  },
  {
    id: 'p014',
    name: 'Sun Lounger Premium',
    nameEn: 'Sun Lounger Premium',
    nameTh: 'เก้าอี้เลาจน์กลางแจ้ง พรีเมียม',
    nameZh: '高级户外躺椅',
    nameJa: 'プレミアムサンラウンジャー',
    nameLa: 'ເກົ້າອີ້ນອນ ໂດ່ ກາງແຈ້ງ',
    category: 'outdoor',
    price: 12800,
    material: 'หวายสังเคราะห์ + อลูมิเนียม',
    dimensions: '190 × 68 × 35 cm',
    brand: 'Sivili Outdoor',
    colors: ['#F5F0E8', '#8B6914'],
    images: FURNITURE_IMAGES.outdoor,
    description: 'Adjustable premium sun lounger with waterproof cushion, perfect for poolside.',
    descriptionTh: 'เก้าอี้นอนเลาจน์ปรับได้ กันน้ำ เหมาะริมสระว่ายน้ำหรือสวน',
    stock: 9,
    rating: 4.7,
    reviewCount: 28,
    isFeatured: false,
    isNew: false,
  },
  {
    id: 'p015',
    name: 'Bookshelf Ladder 5-Tier',
    nameEn: 'Bookshelf Ladder 5-Tier',
    nameTh: 'ชั้นวางหนังสือ 5 ชั้น ทรงบันได',
    nameZh: '5层梯形书架',
    nameJa: '5段ラダーブックシェルフ',
    nameLa: 'ຊັ້ນວາງໜັງສື 5 ຊັ້ນ ຊັ້ນບັນໄດ',
    category: 'office',
    price: 6800,
    material: 'ไม้สน + เหล็กคอ',
    dimensions: '60 × 30 × 180 cm',
    brand: 'Sivili Home',
    colors: ['#8B6914', '#2C2C2C', '#FFFFFF'],
    images: FURNITURE_IMAGES.office,
    description: 'Leaning ladder bookshelf combining pine wood and powder-coated steel frame.',
    descriptionTh: 'ชั้นวางหนังสือทรงบันได ไม้สน + โครงเหล็ก ดีไซน์เรียบง่ายดูทันสมัย',
    stock: 22,
    rating: 4.3,
    reviewCount: 55,
    isFeatured: false,
    isNew: true,
  },
  {
    id: 'p016',
    name: 'Luxury Sectional Sofa L-Shape',
    nameEn: 'Luxury Sectional Sofa L-Shape',
    nameTh: 'โซฟาตัวแอล หรูหรา',
    nameZh: 'L形豪华组合沙发',
    nameJa: 'ラグジュアリーL字型ソファ',
    nameLa: 'ໂຊຟາ L ຮູບ ຫຼູຫຼາ',
    category: 'living',
    price: 58000,
    originalPrice: 68000,
    material: 'หนังแท้ / Genuine Leather',
    dimensions: '280 × 180 × 90 cm',
    brand: 'Sivili Luxury',
    colors: ['#2C1810', '#8B7355', '#F5F0E8'],
    images: FURNITURE_IMAGES.sofa,
    description: 'Premium L-shaped sectional in genuine leather with electric recliner function.',
    descriptionTh: 'โซฟาตัวแอล หนังแท้พรีเมียม ระบบเอนไฟฟ้า สุดหรูหรา',
    stock: 3,
    rating: 5.0,
    reviewCount: 19,
    isFeatured: true,
    isNew: false,
  },
  {
    id: 'p017',
    name: 'Kids Study Desk & Chair Set',
    nameEn: 'Kids Study Desk & Chair Set',
    nameTh: 'ชุดโต๊ะเรียนเด็กพร้อมเก้าอี้',
    nameZh: '儿童学习桌椅套装',
    nameJa: 'キッズ学習机とチェアセット',
    nameLa: 'ຊຸດໂຕະຮຽນເດັກ + ເກົ້າອີ້',
    category: 'office',
    price: 8900,
    material: 'ไม้ MDF เคลือบสี / Painted MDF',
    dimensions: 'โต๊ะ: 100 × 55 × 60-75 cm',
    brand: 'Sivili Kids',
    colors: ['#FFFFFF', '#F5F0E8', '#3B82F6'],
    images: FURNITURE_IMAGES.office,
    description: 'Height-adjustable kids study desk and ergonomic chair set in cheerful colors.',
    descriptionTh: 'ชุดโต๊ะเรียนปรับความสูงได้ สำหรับเด็ก เก้าอี้เออร์กอนอมิกเด็ก',
    stock: 16,
    rating: 4.6,
    reviewCount: 83,
    isFeatured: false,
    isNew: false,
  },
  {
    id: 'p018',
    name: 'Marble-Top Side Table',
    nameEn: 'Marble-Top Side Table',
    nameTh: 'โต๊ะข้างหินอ่อน',
    nameZh: '大理石边桌',
    nameJa: 'マーブルトップサイドテーブル',
    nameLa: 'ໂຕະຂ້າງ ໜ້າຫີນ',
    category: 'living',
    price: 5400,
    material: 'หินอ่อนแท้ + ขาทอง / Marble + Gold Legs',
    dimensions: '45 × 45 × 55 cm',
    brand: 'Sivili Luxury',
    colors: ['#FFFFFF', '#F5F0E8'],
    images: FURNITURE_IMAGES.table,
    description: 'Elegant marble-top accent table with slim gold-tone metal legs.',
    descriptionTh: 'โต๊ะข้างหินอ่อนแท้ ขาเหล็กชุบทอง หรูหราสง่างาม',
    stock: 11,
    rating: 4.8,
    reviewCount: 44,
    isFeatured: false,
    isNew: true,
  },
  {
    id: 'p019',
    name: 'Storage Ottoman Bench',
    nameEn: 'Storage Ottoman Bench',
    nameTh: 'ม้านั่งออตโตมันเก็บของ',
    nameZh: '收纳脚凳长凳',
    nameJa: 'ストレージオットマンベンチ',
    nameLa: 'ມ້ານັ່ງ Ottoman ເກັບຂອງ',
    category: 'bedroom',
    price: 6200,
    material: 'ผ้าลินิน / Linen Fabric',
    dimensions: '120 × 40 × 45 cm',
    brand: 'Sivili Home',
    colors: ['#F5F0E8', '#5B6B7A', '#8B7355'],
    images: FURNITURE_IMAGES.sofa,
    description: 'Versatile storage ottoman bench that doubles as seating and hidden storage.',
    descriptionTh: 'ม้านั่งออตโตมันเก็บของ 2-in-1 นั่งได้และเก็บของได้ในตัวเดียว',
    stock: 19,
    rating: 4.4,
    reviewCount: 37,
    isFeatured: false,
    isNew: false,
  },
  {
    id: 'p020',
    name: 'Round Dining Table 120cm',
    nameEn: 'Round Dining Table 120cm',
    nameTh: 'โต๊ะทานข้าวทรงกลม 120 ซม.',
    nameZh: '120cm圆形餐桌',
    nameJa: 'ラウンドダイニングテーブル120cm',
    nameLa: 'ໂຕະກິນເຂົ້າ ຮູບວົງມົນ 120 ຊມ',
    category: 'dining',
    price: 11500,
    material: 'ไม้สักแท้ / Solid Teak Wood',
    dimensions: 'Ø120 × 75 cm',
    brand: 'Sivili Home',
    colors: ['#8B6914', '#5C4A37'],
    images: FURNITURE_IMAGES.dining,
    description: 'Round solid teak dining table, seats 4-6 comfortably. Timeless and elegant.',
    descriptionTh: 'โต๊ะทานข้าวทรงกลมไม้สักแท้ นั่งได้ 4-6 คน คลาสสิกและหรูหรา',
    stock: 6,
    rating: 4.7,
    reviewCount: 49,
    isFeatured: false,
    isNew: false,
  },
];

// In-memory users store (resets on server restart)
export const USERS: User[] = [
  {
    id: 'u001',
    name: 'Admin Sivili',
    email: 'admin@sivili.com',
    password: 'admin1234',
    role: 'admin',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'u002',
    name: 'สมชาย ใจดี',
    email: 'somchai@example.com',
    password: 'user1234',
    role: 'customer',
    createdAt: '2026-03-15T00:00:00Z',
  },
];

// In-memory orders store
export const ORDERS: Order[] = [
  {
    id: 'ord001',
    userId: 'u002',
    items: [
      { productId: 'p001', quantity: 1, price: 32900 },
      { productId: 'p007', quantity: 2, price: 9900 },
    ],
    total: 52700,
    status: 'delivered',
    paymentMethod: 'credit_card',
    createdAt: '2026-06-10T10:30:00Z',
  },
  {
    id: 'ord002',
    userId: 'u002',
    items: [{ productId: 'p010', quantity: 1, price: 15900 }],
    total: 15900,
    status: 'shipping',
    paymentMethod: 'qr_code',
    createdAt: '2026-06-25T14:00:00Z',
  },
];

// Helper to generate simple token
export function generateToken(user: Omit<User, 'password'>): string {
  const payload = JSON.stringify({ id: user.id, email: user.email, role: user.role });
  return Buffer.from(payload).toString('base64');
}

export function verifyToken(token: string): { id: string; email: string; role: string } | null {
  try {
    const payload = Buffer.from(token, 'base64').toString('utf-8');
    return JSON.parse(payload);
  } catch {
    return null;
  }
}
